In [2]:
import pandas as pd

In [3]:
url1 ="https://raw.githubusercontent.com/polinaprinii/DAP-Project/main/Cases_and_Death_Rates/Data/Data%20for%20Multiple%20Linear%20Regression/Global_and_US_Confirmed_Cases_And_Deaths.csv?token=ASV4RS6WZYFUWQ325ZCQI3TBXDRT6"
cases_deaths =pd.read_csv(url1)

url2 = "https://raw.githubusercontent.com/polinaprinii/DAP-Project/main/Restriction%20and%20Testing%20Analysis/Restrictions/restrictions.csv?token=ASV4RS2EE7HC7DMD6OFAR4DBW6TQ6"
restrictions = pd.read_csv(url2)

url3 = "https://raw.githubusercontent.com/polinaprinii/DAP-Project/main/Restriction%20and%20Testing%20Analysis/world%20testing/testing.csv?token=ASV4RS424SAEGIM3KBA7P23BW6TTM"
tests = pd.read_csv(url3)

url4 = "https://raw.githubusercontent.com/polinaprinii/DAP-Project/main/Vaccine_Analysis_by_Country/Main%20Project/CSV%20Files/finalexport.csv?token=ASV4RSZSY4LEVQIIVPRB43LBW6WDI"
vaccine = pd.read_csv(url4)

In [51]:
merge1 = pd.merge(restrictions, tests, how="outer", left_on =["isocode","country"], right_on = ["isocode","country"])
merge1 = merge1[['isocode','country','MaxStringencyIndex','MeanStringencyIndex','MaxFacialCoverings','MeanFacialCoverings','MaxStayHome','MeanStayHome','tests']]
merge1

,isocode,country,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,tests
0,AFG,Afghanistan,56.02,30.132369,3.0,2.510769,3.0,0.135385,0.0
1,ALB,Albania,63.89,49.158252,4.0,3.046012,2.0,2.000000,81840662.0
2,DZA,Algeria,85.19,60.175902,3.0,3.000000,2.0,1.785933,0.0
3,AND,Andorra,65.74,50.570954,3.0,2.581538,2.0,0.080000,8830188.0
4,AGO,Angola,65.74,56.662515,4.0,2.960123,2.0,1.061350,0.0
...,...,...,...,...,...,...,...,...,...
255,TUV,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,0.0
256,OWID_UMC,Upper middle income,NaN,NaN,NaN,NaN,NaN,NaN,0.0
257,VAT,Vatican,NaN,NaN,NaN,NaN,NaN,NaN,0.0
258,WLF,Wallis and Futuna,NaN,NaN,NaN,NaN,NaN,NaN,0.0
259,OWID_WRL,World,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [57]:
merge2 = pd.merge(merge1,cases_deaths,how="outer", left_on =["isocode","country"], right_on = ["isocode","country"])
merge2 = merge2[['isocode','MaxStringencyIndex','MeanStringencyIndex','MaxFacialCoverings','MeanFacialCoverings','MaxStayHome','MeanStayHome','tests','country','Confirmed','Deaths']]
merge2

,isocode,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,tests,country,Confirmed,Deaths
0,AFG,56.02,30.132369,3.0,2.510769,3.0,0.135385,0.0,Afghanistan,157032.0,7306.0
1,ALB,63.89,49.158252,4.0,3.046012,2.0,2.000000,81840662.0,Albania,197776.0,3063.0
2,DZA,85.19,60.175902,3.0,3.000000,2.0,1.785933,0.0,Algeria,209463.0,6035.0
3,AND,65.74,50.570954,3.0,2.581538,2.0,0.080000,8830188.0,Andorra,16426.0,131.0
4,AGO,65.74,56.662515,4.0,2.960123,2.0,1.061350,0.0,Angola,65080.0,1731.0
...,...,...,...,...,...,...,...,...,...,...,...
267,SRB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kosovo,161037.0,2983.0
268,TLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Timor-Leste,19820.0,122.0
269,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,47877773.0,772208.0
270,VAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Holy See,27.0,0.0
271,VIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,7490.0,85.0

In [58]:
merge3 = pd.merge(merge2, vaccine, how="outer", left_on =["isocode","country"], right_on = ["isocode","country"])
merge3

,isocode,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,tests,country,Confirmed,Deaths,totalvaccinations,totalbooster,fullyvaccinated
0,AFG,56.02,30.132369,3.0,2.510769,3.0,0.135385,0.0,Afghanistan,157032.0,7306.0,0.0,0.0,0.0
1,ALB,63.89,49.158252,4.0,3.046012,2.0,2.000000,81840662.0,Albania,197776.0,3063.0,2074670.0,57338.0,951371.0
2,DZA,85.19,60.175902,3.0,3.000000,2.0,1.785933,0.0,Algeria,209463.0,6035.0,0.0,0.0,0.0
3,AND,65.74,50.570954,3.0,2.581538,2.0,0.080000,8830188.0,Andorra,16426.0,131.0,104534.0,0.0,49535.0
4,AGO,65.74,56.662515,4.0,2.960123,2.0,1.061350,0.0,Angola,65080.0,1731.0,9026310.0,0.0,2760266.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,VIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,7490.0,85.0,NaN,NaN,NaN
272,OWID_ENG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,England,NaN,NaN,95144934.0,13697204.0,38764212.0
273,OWID_SCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scotland,NaN,NaN,9820657.0,1535623.0,3942927.0
274,OWID_WLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wales,NaN,NaN,5531897.0,806297.0,2260038.0
275,OWID_NIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Ireland,NaN,NaN,2970478.0,344451.0,1265081.0

In [60]:
merge3 = merge3[['isocode','MaxStringencyIndex','MeanStringencyIndex','MaxFacialCoverings','MeanFacialCoverings','MaxStayHome','MeanStayHome','tests','country','Confirmed','Deaths']]
merge3

,isocode,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,tests,country,Confirmed,Deaths
0,AFG,56.02,30.132369,3.0,2.510769,3.0,0.135385,0.0,Afghanistan,157032.0,7306.0
1,ALB,63.89,49.158252,4.0,3.046012,2.0,2.000000,81840662.0,Albania,197776.0,3063.0
2,DZA,85.19,60.175902,3.0,3.000000,2.0,1.785933,0.0,Algeria,209463.0,6035.0
3,AND,65.74,50.570954,3.0,2.581538,2.0,0.080000,8830188.0,Andorra,16426.0,131.0
4,AGO,65.74,56.662515,4.0,2.960123,2.0,1.061350,0.0,Angola,65080.0,1731.0
...,...,...,...,...,...,...,...,...,...,...,...
271,VIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,7490.0,85.0
272,OWID_ENG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,England,NaN,NaN
273,OWID_SCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scotland,NaN,NaN
274,OWID_WLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wales,NaN,NaN
275,OWID_NIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Ireland,NaN,NaN

In [63]:
finalmerge = merge3[['isocode','country','Confirmed','Deaths','tests','MaxStringencyIndex','MeanStringencyIndex','MaxFacialCoverings','MeanFacialCoverings','MaxStayHome','MeanStayHome']]
finalmerge = pd.merge(finalmerge, vaccine,how="outer", left_on =["isocode","country"], right_on = ["isocode","country"])
finalmerge = finalmerge[['isocode','country','Confirmed','Deaths','tests','MaxStringencyIndex','MeanStringencyIndex','MaxFacialCoverings','MeanFacialCoverings','MaxStayHome','MeanStayHome','totalvaccinations','totalbooster','fullyvaccinated']]
finalmerge

,isocode,country,Confirmed,Deaths,tests,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,totalvaccinations,totalbooster,fullyvaccinated
0,AFG,Afghanistan,157032.0,7306.0,0.0,56.02,30.132369,3.0,2.510769,3.0,0.135385,0.0,0.0,0.0
1,ALB,Albania,197776.0,3063.0,81840662.0,63.89,49.158252,4.0,3.046012,2.0,2.000000,2074670.0,57338.0,951371.0
2,DZA,Algeria,209463.0,6035.0,0.0,85.19,60.175902,3.0,3.000000,2.0,1.785933,0.0,0.0,0.0
3,AND,Andorra,16426.0,131.0,8830188.0,65.74,50.570954,3.0,2.581538,2.0,0.080000,104534.0,0.0,49535.0
4,AGO,Angola,65080.0,1731.0,0.0,65.74,56.662515,4.0,2.960123,2.0,1.061350,9026310.0,0.0,2760266.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,VIR,US,7490.0,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,OWID_ENG,England,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95144934.0,13697204.0,38764212.0
273,OWID_SCT,Scotland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9820657.0,1535623.0,3942927.0
274,OWID_WLS,Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5531897.0,806297.0,2260038.0
275,OWID_NIR,Northern Ireland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2970478.0,344451.0,1265081.0

In [66]:
finalmerge = finalmerge.drop(labels = range(187,276),axis = 0)
finalmerge

,isocode,country,Confirmed,Deaths,tests,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,totalvaccinations,totalbooster,fullyvaccinated
0,AFG,Afghanistan,157032.0,7306.0,0.0,56.02,30.132369,3.0,2.510769,3.0,0.135385,0.0,0.0,0.0
1,ALB,Albania,197776.0,3063.0,81840662.0,63.89,49.158252,4.0,3.046012,2.0,2.000000,2074670.0,57338.0,951371.0
2,DZA,Algeria,209463.0,6035.0,0.0,85.19,60.175902,3.0,3.000000,2.0,1.785933,0.0,0.0,0.0
3,AND,Andorra,16426.0,131.0,8830188.0,65.74,50.570954,3.0,2.581538,2.0,0.080000,104534.0,0.0,49535.0
4,AGO,Angola,65080.0,1731.0,0.0,65.74,56.662515,4.0,2.960123,2.0,1.061350,9026310.0,0.0,2760266.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,YEM,Yemen,9972.0,1942.0,0.0,37.96,29.904373,2.0,1.513761,2.0,1.633028,0.0,0.0,0.0
183,ZMB,Zambia,210099.0,3667.0,559230229.0,60.19,42.325291,4.0,2.892966,1.0,0.290520,1057879.0,0.0,667433.0
184,ZWE,Zimbabwe,133747.0,4703.0,246350739.0,87.96,61.841346,NaN,NaN,2.0,1.813456,6486873.0,0.0,2767243.0
185,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
finalmerge.to_csv('D:/Git/DAP-Project/Linear Regression/finaldataset.csv',encoding = 'utf-8')