In [6]:
import pandas as pd

In [43]:
url1 ="https://raw.githubusercontent.com/polinaprinii/DAP-Project/main/Cases_and_Death_Rates/Data/who_global_confirmed_Cases.csv?token=ASV4RS5HYMJRQUOJX6TC45LBW6UQO"
cases =pd.read_csv(url1)

url2 = "https://raw.githubusercontent.com/polinaprinii/DAP-Project/main/Cases_and_Death_Rates/Data/who_global_confirmed_Cases.csv?token=ASV4RSYJBYV35MVVQQYFZBTBW6UOI"
deaths = pd.read_csv(url2)

url3 = "https://raw.githubusercontent.com/polinaprinii/DAP-Project/main/Restriction%20and%20Testing%20Analysis/Restrictions/restrictions.csv?token=ASV4RS2EE7HC7DMD6OFAR4DBW6TQ6"
restrictions = pd.read_csv(url3)

url4 = "https://raw.githubusercontent.com/polinaprinii/DAP-Project/main/Restriction%20and%20Testing%20Analysis/world%20testing/testing.csv?token=ASV4RS424SAEGIM3KBA7P23BW6TTM"
tests = pd.read_csv(url4)

url5 = "https://raw.githubusercontent.com/polinaprinii/DAP-Project/main/Vaccine_Analysis_by_Country/Main%20Project/CSV%20Files/finalexport.csv?token=ASV4RSZSY4LEVQIIVPRB43LBW6WDI"
vaccine = pd.read_csv(url5)

In [27]:
merge1 = pd.merge(restrictions, tests, on ="isocode")
merge1 = merge1[['isocode','country_x','MaxStringencyIndex','MeanStringencyIndex','MaxFacialCoverings','MeanFacialCoverings','MaxStayHome','MeanStayHome','tests']]
merge1

,isocode,country_x,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,tests
0,AFG,Afghanistan,56.02,30.132369,3.0,2.510769,3.0,0.135385,0
1,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,ALB,Albania,63.89,49.158252,4.0,3.046012,2.0,2.000000,81840662
3,DZA,Algeria,85.19,60.175902,3.0,3.000000,2.0,1.785933,0
4,AND,Andorra,65.74,50.570954,3.0,2.581538,2.0,0.080000,8830188
...,...,...,...,...,...,...,...,...,...
197,VEN,Venezuela,97.22,82.525443,4.0,4.000000,3.0,1.993884,0
198,VNM,Vietnam,79.17,68.847538,3.0,3.000000,2.0,1.683077,1518364936
199,YEM,Yemen,37.96,29.904373,2.0,1.513761,2.0,1.633028,0
200,ZMB,Zambia,60.19,42.325291,4.0,2.892966,1.0,0.290520,559230229
201,ZWE,Zimbabwe,87.96,61.841346,NaN,NaN,2.0,1.813456,246350739

In [32]:
merge2 = pd.merge(merge1,cases, on="isocode")
merge2 = merge2[['isocode','MaxStringencyIndex','MeanStringencyIndex','MaxFacialCoverings','MeanFacialCoverings','MaxStayHome','MeanStayHome','tests','country','12/05/2021']]
merge2 = merge2.rename(columns = {'12/05/2021': 'cases'})
merge2

,isocode,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,tests,country,cases
0,AFG,56.02,30.132369,3.0,2.510769,3.0,0.135385,0,Afghanistan,157445
1,AFG,NaN,NaN,NaN,NaN,NaN,NaN,0,Afghanistan,157445
2,ALB,63.89,49.158252,4.0,3.046012,2.0,2.000000,81840662,Albania,201730
3,DZA,85.19,60.175902,3.0,3.000000,2.0,1.785933,0,Algeria,211469
4,AND,65.74,50.570954,3.0,2.581538,2.0,0.080000,8830188,Andorra,18010
...,...,...,...,...,...,...,...,...,...,...
254,UZB,71.30,45.149602,3.0,2.944954,1.0,0.094801,0,Uzbekistan,194333
255,VUT,22.22,21.498226,1.0,0.088685,0.0,0.000000,0,Vanuatu,6
256,YEM,37.96,29.904373,2.0,1.513761,2.0,1.633028,0,Yemen,10025
257,ZMB,60.19,42.325291,4.0,2.892966,1.0,0.290520,559230229,Zambia,210312
258,ZWE,87.96,61.841346,NaN,NaN,2.0,1.813456,246350739,Zimbabwe,139046

In [37]:
merge3 = pd.merge(merge2, deaths, on ="isocode")
merge3

,isocode,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,tests,country_x,cases,country_y,12/05/2021
0,AFG,56.02,30.132369,3.0,2.510769,3.0,0.135385,0,Afghanistan,157445,Afghanistan,157445
1,AFG,NaN,NaN,NaN,NaN,NaN,NaN,0,Afghanistan,157445,Afghanistan,157445
2,ALB,63.89,49.158252,4.0,3.046012,2.0,2.000000,81840662,Albania,201730,Albania,201730
3,DZA,85.19,60.175902,3.0,3.000000,2.0,1.785933,0,Algeria,211469,Algeria,211469
4,AND,65.74,50.570954,3.0,2.581538,2.0,0.080000,8830188,Andorra,18010,Andorra,18010
...,...,...,...,...,...,...,...,...,...,...,...,...
1964,UZB,71.30,45.149602,3.0,2.944954,1.0,0.094801,0,Uzbekistan,194333,Uzbekistan,194333
1965,VUT,22.22,21.498226,1.0,0.088685,0.0,0.000000,0,Vanuatu,6,Vanuatu,6
1966,YEM,37.96,29.904373,2.0,1.513761,2.0,1.633028,0,Yemen,10025,Yemen,10025
1967,ZMB,60.19,42.325291,4.0,2.892966,1.0,0.290520,559230229,Zambia,210312,Zambia,210312
1968,ZWE,87.96,61.841346,NaN,NaN,2.0,1.813456,246350739,Zimbabwe,139046,Zimbabwe,139046

In [39]:
merge3 = merge3[['isocode','MaxStringencyIndex','MeanStringencyIndex','MaxFacialCoverings','MeanFacialCoverings','MaxStayHome','MeanStayHome','tests','country_x','cases','12/05/2021']]
merge3

,isocode,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,tests,country_x,cases,12/05/2021
0,AFG,56.02,30.132369,3.0,2.510769,3.0,0.135385,0,Afghanistan,157445,157445
1,AFG,NaN,NaN,NaN,NaN,NaN,NaN,0,Afghanistan,157445,157445
2,ALB,63.89,49.158252,4.0,3.046012,2.0,2.000000,81840662,Albania,201730,201730
3,DZA,85.19,60.175902,3.0,3.000000,2.0,1.785933,0,Algeria,211469,211469
4,AND,65.74,50.570954,3.0,2.581538,2.0,0.080000,8830188,Andorra,18010,18010
...,...,...,...,...,...,...,...,...,...,...,...
1964,UZB,71.30,45.149602,3.0,2.944954,1.0,0.094801,0,Uzbekistan,194333,194333
1965,VUT,22.22,21.498226,1.0,0.088685,0.0,0.000000,0,Vanuatu,6,6
1966,YEM,37.96,29.904373,2.0,1.513761,2.0,1.633028,0,Yemen,10025,10025
1967,ZMB,60.19,42.325291,4.0,2.892966,1.0,0.290520,559230229,Zambia,210312,210312
1968,ZWE,87.96,61.841346,NaN,NaN,2.0,1.813456,246350739,Zimbabwe,139046,139046

In [41]:
merge3 = merge3.rename(columns = {'12/05/2021': 'deaths','country_x':'country'})
merge3

,isocode,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,tests,country,cases,deaths
0,AFG,56.02,30.132369,3.0,2.510769,3.0,0.135385,0,Afghanistan,157445,157445
1,AFG,NaN,NaN,NaN,NaN,NaN,NaN,0,Afghanistan,157445,157445
2,ALB,63.89,49.158252,4.0,3.046012,2.0,2.000000,81840662,Albania,201730,201730
3,DZA,85.19,60.175902,3.0,3.000000,2.0,1.785933,0,Algeria,211469,211469
4,AND,65.74,50.570954,3.0,2.581538,2.0,0.080000,8830188,Andorra,18010,18010
...,...,...,...,...,...,...,...,...,...,...,...
1964,UZB,71.30,45.149602,3.0,2.944954,1.0,0.094801,0,Uzbekistan,194333,194333
1965,VUT,22.22,21.498226,1.0,0.088685,0.0,0.000000,0,Vanuatu,6,6
1966,YEM,37.96,29.904373,2.0,1.513761,2.0,1.633028,0,Yemen,10025,10025
1967,ZMB,60.19,42.325291,4.0,2.892966,1.0,0.290520,559230229,Zambia,210312,210312
1968,ZWE,87.96,61.841346,NaN,NaN,2.0,1.813456,246350739,Zimbabwe,139046,139046

In [49]:
finalmerge = merge3[['isocode','country','cases','deaths','tests','MaxStringencyIndex','MeanStringencyIndex','MaxFacialCoverings','MeanFacialCoverings','MaxStayHome','MeanStayHome']]
finalmerge = pd.merge(finalmerge, vaccine, on='isocode')
finalmerge = finalmerge[['isocode','country_x','cases','deaths','tests','MaxStringencyIndex','MeanStringencyIndex','MaxFacialCoverings','MeanFacialCoverings','MaxStayHome','MeanStayHome','totalvaccinations','totalbooster','fullyvaccinated']]
finalmerge = finalmerge.rename(columns = {'country_x':'country'})
finalmerge

,isocode,country,cases,deaths,tests,MaxStringencyIndex,MeanStringencyIndex,MaxFacialCoverings,MeanFacialCoverings,MaxStayHome,MeanStayHome,totalvaccinations,totalbooster,fullyvaccinated
0,ALB,Albania,201730,201730,81840662,63.89,49.158252,4.0,3.046012,2.0,2.000000,2074670.0,57338.0,951371.0
1,DZA,Algeria,211469,211469,0,85.19,60.175902,3.0,3.000000,2.0,1.785933,0.0,0.0,0.0
2,AGO,Angola,65259,65259,0,65.74,56.662515,4.0,2.960123,2.0,1.061350,9026310.0,0.0,2760266.0
3,ARG,Argentina,5340676,5340676,5092574630,84.26,72.205000,3.0,2.965409,2.0,1.858491,0.0,0.0,0.0
4,AUS,Australia,2165,2165,5176200578,78.24,61.566239,4.0,2.822630,2.0,1.027523,38801068.0,375635.0,18533097.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936,URY,Uruguay,400925,400925,772580042,87.04,61.338471,2.0,2.000000,1.0,0.886850,6766558.0,1364138.0,2653424.0
1937,UZB,Uzbekistan,194333,194333,0,71.30,45.149602,3.0,2.944954,1.0,0.094801,0.0,0.0,0.0
1938,YEM,Yemen,10025,10025,0,37.96,29.904373,2.0,1.513761,2.0,1.633028,0.0,0.0,0.0
1939,ZMB,Zambia,210312,210312,559230229,60.19,42.325291,4.0,2.892966,1.0,0.290520,1057879.0,0.0,667433.0
1940,ZWE,Zimbabwe,139046,139046,246350739,87.96,61.841346,NaN,NaN,2.0,1.813456,6486873.0,0.0,2767243.0